name: Auto Scrape Events

on:
  schedule:
    - cron: "0 */6 * * *" # every 6 hours
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install

      - name: Run scraper
        run: python scraper.py

      - name: Commit updated events.json
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add events.json
          git commit -m "🔄 Auto-update events.json [skip ci]" || echo "No changes"
          git push

      - name: Upload debug screenshots
        if: always()
        uses: actions/upload-artifact@v3.1.3
        with:
          name: scraper-screenshots
          path: |
            debug-*.png
